# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: prez.dev
dev_addr: localhost:8001
theme:
  name: material
  favicon: /assets/favicon.ico
  logo: /assets/prez-logo.png
  palette:
    scheme: olis
extra_css:
  - stylesheets/prez.css
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - 'index.md'
  - 'ont.md'
  - 'manifest.md'
  - Roles Vocab: 'mrr.md'
